services:
    nginx:
        container_name: app_shop_nginx
        build:
            context: ./
            dockerfile: docker/nginx/Dockerfile
            target: local
        ports:
            - "80:80"
        environment:
            PHP_HOST: app_shop_php
        volumes:
            - ./app:/var/www
        depends_on:
            - php

    php:
        container_name: app_shop_php
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
            target: local
        environment:
            PHP_IDE_CONFIG: '${PHP_IDE_CONFIG:-serverName=shop}'
        volumes:
            - ./app:/var/www
            - ./docker/php/conf/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/php/conf/php.local.ini:/usr/local/etc/php/conf.d/docker-php-local.ini

    db:
        image: postgres:17.2-alpine
        container_name: app_shop_db
        restart: always
        shm_size: 128mb
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: shop_db
        ports:
            - "5432:5432"
        volumes:
            - postgres:/var/lib/postgresql/data:rw

volumes:
    postgres: