api_platform:
    title: Shop CRUD Api Doc
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']

    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
    formats:
        json: ['application/json']
    error_formats:
        jsonproblem: ['application/problem+json']

    mapping:
        paths: ['%kernel.project_dir%/src/Doctrine/Entity']
